pipeline:
  trigger:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    deploy_to: ${DRONE_DEPLOY_TO}
    secrets:
      - drone_token
    when:
      event: deployment

  update:
    image: node:10
    secrets:
      - github_access_token
    commands:
      - npm ci
      - bin/update --repo UKHomeOffice/asl-deployments --token $${GITHUB_ACCESS_TOKEN} --service $${DEPLOY_SERVICE} --version $${DEPLOY_VERSION}
    when:
      event: deployment
