
kind: pipeline
name: default
type: kubernetes
steps:
  - name: install
    image: node:16
    commands:
      - npm ci
  - name: test
    image: node:16
    commands:
      - npm test
  - name: docker build
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      # wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker build -t asl-deploy-bot .
  - name: docker push
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-deploy-bot quay.io/ukhomeofficedigital/asl-deploy-bot:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-deploy-bot:$${DRONE_COMMIT_SHA}
      - docker tag asl-deploy-bot quay.io/ukhomeofficedigital/asl-deploy-bot:latest
      - docker push quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    when:
      event: push
      branch: master

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
