pipeline:
  trigger:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    drone_token: ${DRONE_TOKEN}
    repo: ${REPO}
    number: ${NUMBER}
    deploy_to: ${DRONE_DEPLOY_TO}
    when:
      event: deployment
