pipeline:
  trigger:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    deploy_to: ${DRONE_DEPLOY_TO}
    secrets:
      - drone_token
    when:
      event: deployment

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl-deploy-bot .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-deploy-bot quay.io/ukhomeofficedigital/asl-deploy-bot:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl-deploy-bot:$${DRONE_COMMIT_SHA}
      - docker tag asl-deploy-bot quay.io/ukhomeofficedigital/asl-deploy-bot:latest
      - docker push quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    when:
      branch: master
      event: push
