pipeline:
  trigger:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    deploy_to: ${DRONE_DEPLOY_TO}
    when:
      event: deployment
